### ISSUE TITLE
Can't build with AIR 3.7

### ISSUE THREAD

**Issue by kanryu** [freshplanet/ANE-Push-Notification#26]
Hi, I'm trying to run the ANE in iOS, but building failed.
because recently AIR SDK has Push notification support within itself.
So, the following errors.

C:\Home\src\flex\PushSample\bin-debug>adt -package -target ipa-test-interpreter -hideAneLi
bSymbols no -provisioning-profile C:\Home\src\flex\PushSample\dpika_airmobilesample-2.mobil
eprovision -storetype pkcs12 -keystore C:\Home\src\flex\FlexMobileSample2\pikapika_dist.p12
 PushSample.ipa PushSample-app.xml DebugHostInfo.xml PushSample.swf -extdir "C:\Users\h_ut
sunomiya\Adobe Flash Builder 4.7.metadata.plugins\com.adobe.flexbuilder.project.ui\ANEFi
les\PushSample\com.adobe.flexide.multiplatform.ios.platform"
password:
duplicate symbol _FRPE_ApplicationDidReceiveRemoteNotificationKey in:
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libRuntimeInterpreter.arm-
air.a(CTAIRAppController+PrivateExtensions.o)
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libNotification.arm-air.a(
CTAIRAppController+NotificationExtensions.o)
duplicate symbol _FRPE_ApplicationDidReceiveRemoteNotification in:
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libRuntimeInterpreter.arm-
air.a(CTAIRAppController+PrivateExtensions.o)
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libNotification.arm-air.a(
CTAIRAppController+NotificationExtensions.o)
duplicate symbol _FRPE_ApplicationDidRegisterForRemoteNotificationsWithDeviceTokenKey in:
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libRuntimeInterpreter.arm-
air.a(CTAIRAppController+PrivateExtensions.o)
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libNotification.arm-air.a(
CTAIRAppController+NotificationExtensions.o)
duplicate symbol _FRPE_ApplicationDidRegisterForRemoteNotificationsWithDeviceToken in:
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libRuntimeInterpreter.arm-
air.a(CTAIRAppController+PrivateExtensions.o)
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libNotification.arm-air.a(
CTAIRAppController+NotificationExtensions.o)
duplicate symbol _FRPE_ApplicationDidFailToRegisterForRemoteNotificationsWithErrorKey in:
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libRuntimeInterpreter.arm-
air.a(CTAIRAppController+PrivateExtensions.o)
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libNotification.arm-air.a(
CTAIRAppController+NotificationExtensions.o)
duplicate symbol _FRPE_ApplicationDidFailToRegisterForRemoteNotificationsWithError in:
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libRuntimeInterpreter.arm-
air.a(CTAIRAppController+PrivateExtensions.o)
    C:\Home\local\Adobe\AIRSDK_Compiler-3.7.0\lib\aot/lib/libNotification.arm-air.a(
CTAIRAppController+NotificationExtensions.o)
ld: 6 duplicate symbols for architecture armv7
Compilation failed while executing : ld64

comments?
